name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: yarn install
    - run: yarn tsc
    - run: yarn build:backend

    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
    uses: docker/login-action@v3.3.0
    with:
      username: anthonyward
      password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - run: docker build . --file packages/backend/Dockerfile --tag anthonyward/backstage-argo:$(date +%s)

    - run: docker push anthonyward/backstage-argo:$(date +%s)
